name: Maven CI/CD

on:
  push:
    branches: [ main ]

  jobs:
    test_and_build:

      runs-on: ubuntu-latest

      steps:

        - uses: actions/checkout@v2
        - name: Set up JDK 8
          uses: actions/setup-java@v1
          with:
              ava-version: 8
        - name: Test project with Maven
          run: mvn -B test
        - name: Build project with Maven
          run: mvn -B package